/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package intellij.startup.app;

import intellij.startup.list.LinkedList;

import static intellij.startup.utilities.StringUtils.join;
import static intellij.startup.utilities.StringUtils.split;
import static intellij.startup.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
